name: Release
on:
  push:
    branches:
      - "main"
    tags:
      - v*.*.*
jobs:
  build:
    name: ${{ matrix.friendlyName }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        node: ["22.x"]
        os: [macos-14, windows-latest, ubuntu-latest]
        include:
          - os: macos-14
            arch: universal
            friendlyName: macOS
          - os: windows-latest
            arch: x64
            friendlyName: Windows
          - os: ubuntu-latest
            arch: x64
            friendlyName: Ubuntu
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: yarn install && cache
        uses: ./.github/actions/yarn-nm-install

      - name: Package application
        id: packageing
        run: yarn dist
        env:
          USE_HARD_LINKS: "false"

